---
abstract: 'declare class attributes Moose-style... but without Moose'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires: {}
configure_requires:
  CPAN::Meta::Requirements: 2.000
  ExtUtils::MakeMaker: 6.17
conflicts:
  Moo: '== 1.001000'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.009, CPAN::Meta::Converter version 2.120921'
keywords: []
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-ClassAttribute
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
provides:
  Method::Generate::ClassAccessor:
    file: lib/Method/Generate/ClassAccessor.pm
    version: 0.010
  MooX::CaptainHook:
    file: lib/MooX/CaptainHook.pm
    version: 0.010
  MooX::CaptainHook::HandleMoose::Hack:
    file: lib/MooX/CaptainHook.pm
    version: 0.010
  MooX::CaptainHook::OnApplication:
    file: lib/MooX/CaptainHook.pm
    version: 0.010
  MooX::CaptainHook::OnApplication::Moose:
    file: lib/MooX/CaptainHook.pm
    version: 0.010
  MooX::CaptainHook::OnInflation:
    file: lib/MooX/CaptainHook.pm
    version: 0.010
  MooX::ClassAttribute:
    file: lib/MooX/ClassAttribute.pm
    version: 0.010
  MooX::ClassAttribute::HandleMoose:
    file: lib/MooX/ClassAttribute/HandleMoose.pm
    version: 0.010
recommends:
  MooseX::ClassAttribute: 0
requires:
  Moo: 1.000000
  Role::Tiny: 1.000000
  Sub::Exporter::Progressive: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooX-ClassAttribute/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-ClassAttribute
  homepage: https://metacpan.org/release/MooX-ClassAttribute
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moox-classattribute
version: 0.010
x_contributors:
  - 'Dinis Rebolo (DREBOLO) <drebolo@cpan.org>'
